name: Generate npm report
env:
  RUN_NUMBER: ${{ github.run_number }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  build-stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install node 
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install npm
        run: npm install
      - run: npm ci
      - name: run npm audit
        run: npm audit --json