name: Generate npm report
env:
  RUN_NUMBER: ${{ github.run_number }}
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  build-stage:
    runs-on: ubuntu-latest

    steps:

      - name: install node 
        uses: actions/setup-node@v3
        with:
          node-version: '4'
          
      - name: run npm audit
        run: npm audit